site_name: Mbed CE
site_url: https://mbed-ce.dev
repo_url: https://github.com/mbed-ce/mbed-os
theme:
  name: material
  palette:
    primary: custom
  favicon: img/favicon.ico
extra_css:
 - stylesheets/extra.css
plugins:
  - search
  - awesome-nav

# Enable syntax highlighting per https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - attr_list