name: Build and Deploy

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13' 
    - name: Create Venv for Mkdocs
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
    - name: Build Site
      run: |
        source .venv/bin/activate
        mkdocs build

    # Copy the built files to the server (only if this is on main branch)
    - name: Deploy Site
      if: github.ref == 'refs/heads/main'
      uses: easingthemes/ssh-deploy@v5.1.0
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i --delete"
        SOURCE: "site/"
        REMOTE_HOST: mbed-ce.dev
        REMOTE_USER: website-deploy
        TARGET: /var/www/html